"""added StockReport table

Revision ID: 01decfad1312
Revises: 5f6b883c9830
Create Date: 2025-12-19 18:49:07.923161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01decfad1312'
down_revision: Union[str, Sequence[str], None] = '5f6b883c9830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_reports',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('report', sa.String(), nullable=False),
                    sa.Column('created_at', sa.Date(), server_default=sa.text(
                        'CURRENT_DATE'), nullable=True),
                    sa.Column('updated_at', sa.Date(), server_default=sa.text(
                        'CURRENT_DATE'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ticker', 'created_at',
                                        name='uq_ticker_created_at')
                    )
    op.create_index(op.f('ix_stock_reports_ticker'),
                    'stock_reports', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_reports_ticker'), table_name='stock_reports')
    op.drop_table('stock_reports')
    # ### end Alembic commands ###
