"""news db edited

Revision ID: 44beddce0253
Revises: ae571f60eb6e
Create Date: 2025-12-16 16:17:16.052760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44beddce0253'
down_revision: Union[str, Sequence[str], None] = 'ae571f60eb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_news', sa.Column('url', sa.String(), nullable=False))
    op.add_column('stock_news', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('stock_news', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('uq_ticker_url', 'stock_news', ['ticker', 'url'])
    op.add_column('stock_news_chunks', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_news_chunks', 'content')
    op.drop_constraint('uq_ticker_url', 'stock_news', type_='unique')
    op.drop_column('stock_news', 'updated_at')
    op.drop_column('stock_news', 'created_at')
    op.drop_column('stock_news', 'url')
    # ### end Alembic commands ###
