"""init

Revision ID: 4bce1f1fe6f8
Revises: 
Create Date: 2025-12-17 15:46:02.330054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '4bce1f1fe6f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('stock_data',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('ticker', sa.String(), nullable=True),
                    sa.Column('trade_date', sa.DateTime(), nullable=True),
                    sa.Column('open', sa.Float(), nullable=True),
                    sa.Column('high', sa.Float(), nullable=True),
                    sa.Column('low', sa.Float(), nullable=True),
                    sa.Column('close', sa.Float(), nullable=True),
                    sa.Column('volume', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ticker', 'trade_date',
                                        name='uq_ticker_trade_date')
                    )
    op.create_index(op.f('ix_stock_data_ticker'),
                    'stock_data', ['ticker'], unique=False)
    op.create_table('stock_news',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('full_content', sa.String(), nullable=True),
                    sa.Column('published_at', sa.DateTime(), nullable=True),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('url')
                    )
    op.create_index(op.f('ix_stock_news_ticker'),
                    'stock_news', ['ticker'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('provider', sa.String(), nullable=False),
                    sa.Column('provider_id', sa.String(), nullable=False),
                    sa.Column('is_authorized', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'provider', 'provider_id', name='uq_provider_user')
                    )
    op.create_index('ix_provider_user', 'users', [
                    'provider', 'provider_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('stock_news_chunks',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=768), nullable=True),
                    sa.Column('content', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['parent_id'], ['stock_news.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_stock_news_chunks_ticker'),
                    'stock_news_chunks', ['ticker'], unique=False)
    op.create_table('subscriptions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.String(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('chat_id'),
                    sa.UniqueConstraint('chat_id', name='uq_chat_id')
                    )
    op.create_index(op.f('ix_subscriptions_id'),
                    'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_stock_news_chunks_ticker'),
                  table_name='stock_news_chunks')
    op.drop_table('stock_news_chunks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_provider_user', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_news_ticker'), table_name='stock_news')
    op.drop_table('stock_news')
    op.drop_index(op.f('ix_stock_data_ticker'), table_name='stock_data')
    op.drop_table('stock_data')
    # ### end Alembic commands ###
