"""Fix db

Revision ID: 75e4f4e27242
Revises: cd54a32cc032
Create Date: 2025-12-17 17:12:50.828805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e4f4e27242'
down_revision: Union[str, Sequence[str], None] = 'cd54a32cc032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_data', sa.Column('open_price', sa.Float(), nullable=True))
    op.add_column('stock_data', sa.Column('high_price', sa.Float(), nullable=True))
    op.add_column('stock_data', sa.Column('low_price', sa.Float(), nullable=True))
    op.add_column('stock_data', sa.Column('close_price', sa.Float(), nullable=True))
    op.drop_column('stock_data', 'open')
    op.drop_column('stock_data', 'close')
    op.drop_column('stock_data', 'high')
    op.drop_column('stock_data', 'low')
    op.create_unique_constraint('uq_user_chat_ticker', 'subscriptions', ['user_id', 'chat_id', 'ticker'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_chat_ticker', 'subscriptions', type_='unique')
    op.add_column('stock_data', sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_data', sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_data', sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_data', sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('stock_data', 'close_price')
    op.drop_column('stock_data', 'low_price')
    op.drop_column('stock_data', 'high_price')
    op.drop_column('stock_data', 'open_price')
    # ### end Alembic commands ###
