"""stock news unique column update

Revision ID: 7824bf0c33a3
Revises: 44beddce0253
Create Date: 2025-12-16 17:35:43.026137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7824bf0c33a3'
down_revision: Union[str, Sequence[str], None] = '44beddce0253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_news_published_at'), table_name='stock_news')
    op.drop_constraint(op.f('uq_ticker_url'), 'stock_news', type_='unique')
    op.create_unique_constraint(None, 'stock_news', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_news', type_='unique')
    op.create_unique_constraint(op.f('uq_ticker_url'), 'stock_news', ['ticker', 'url'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_stock_news_published_at'), 'stock_news', ['published_at'], unique=False)
    # ### end Alembic commands ###
