"""news db

Revision ID: ae571f60eb6e
Revises: 16b5d1edf061
Create Date: 2025-12-16 16:13:12.771076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'ae571f60eb6e'
down_revision: Union[str, Sequence[str], None] = '16b5d1edf061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_news_chunks',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=768), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['parent_id'], ['stock_news.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_stock_news_chunks_ticker'),
                    'stock_news_chunks', ['ticker'], unique=False)
    op.add_column('stock_news', sa.Column(
        'full_content', sa.String(), nullable=True))
    op.drop_column('stock_news', 'created_at')
    op.drop_column('stock_news', 'content')
    op.drop_column('stock_news', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_news', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
        dim=768), autoincrement=False, nullable=True))
    op.add_column('stock_news', sa.Column(
        'content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock_news', sa.Column('created_at', postgresql.TIMESTAMP(
    ), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('stock_news', 'full_content')
    op.drop_index(op.f('ix_stock_news_chunks_ticker'),
                  table_name='stock_news_chunks')
    op.drop_table('stock_news_chunks')
    # ### end Alembic commands ###
