"""update subscribes and relations with VectorDB

Revision ID: eff0ff1b092b
Revises: ff5c26b61661
Create Date: 2025-12-17 13:27:16.963040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff0ff1b092b'
down_revision: Union[str, Sequence[str], None] = 'ff5c26b61661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_news_chunks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('subscriptions', sa.Column('chat_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'chat_id')
    op.drop_column('stock_news_chunks', 'updated_at')
    # ### end Alembic commands ###
