"""Add chunk cascading

Revision ID: ff5c26b61661
Revises: 7824bf0c33a3
Create Date: 2025-12-16 17:51:50.800423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5c26b61661'
down_revision: Union[str, Sequence[str], None] = '7824bf0c33a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stock_news_chunks_parent_id_fkey'), 'stock_news_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'stock_news_chunks', 'stock_news', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_news_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('stock_news_chunks_parent_id_fkey'), 'stock_news_chunks', 'stock_news', ['parent_id'], ['id'])
    # ### end Alembic commands ###
